### ISSUE TITLE
I have a issue for train.py?

### ISSUE THREAD

**Issue by bluesky1308** [david8862/keras-YOLOv3-model-set#115]
Dear Bro,

I test train.py with yolo3_mobilenetv2 like below:

!python train.py --model_type=yolo3_mobilenetv2 \
    --anchors_path=configs/yolo3_anchors.txt \
    --model_image_size=416x416 \
    --batch_size=16 \
    --annotation_file=tools/dataset_converter/train2014.txt \
    --val_annotation_file=tools/dataset_converter/val2014.txt \
    --classes_path=configs/coco_classes.txt \
    --optimizer=adam \
    --learning_rate=1e-3 \
    --eval_online \
    --gpu_num=2 \
    --save_eval_checkpoint

A. Would you describe how to set parameter in training with pretrained mobilenetv2-imagenet-keras? 
I see the mobilenetv2-loaded with imagenet weight :  mobilenetv2 = MobileNetV2(input_tensor=inputs, weights='imagenet', include_top=False, alpha=alpha).
           1. --transfer_epoch:
           2. --freeze_level: 
           3. --init_epoch: 
           4. --weights_path : it mean yolo3-mobilenetv2 pretrained weight  or mobilenetv2 pretrained weight from keras?

B. Would you describe how to set parameter in training without any pretrained weight or checkpoint? i want train from scratch with new base model.
           1. --transfer_epoch: 
           2. --freeze_level: 
           3. --init_epoch: 
           4. --weights_path: 

Thank you

**Comment by bluesky1308** [comment]
Could you have a yolov3_mobilenetv2 pretrained model? I dont see it on readme.md

**Comment by david8862** [comment]
Hi @bluesky1308 
A. generally you can just follow default training config in train.py. "--transfer_epoch" could be 10 or 20 in my experience. "--weights_path" means a yolo3_mobilenetv2 pretrained model or weights.

B. If you want to add a new backbone and training from scratch, generally you should

1. create a new backbone definition under common/backbones/
2. register the backbone to [imagenet_training](https://github.com/david8862/keras-YOLOv3-model-set/tree/master/common/backbones/imagenet_training) module and train it with imagenet dataset
3. create corresponding detection model under yolo3/models/, and load imagenet pretrained backbone weights
4. train the detection model on your dataset

I didn't prepare mobilenetv2 pretrained model yet. May add that later if having enough GPU resource

**Comment by bluesky1308** [comment]
Thank you for helping me!!!
