### ISSUE TITLE
Question about using vgg

### ISSUE THREAD

**Issue by yellowjs0304** [david8862/keras-YOLOv3-model-set#116]
Hi, I used your code for detection.

I used "python train.py --model_type=yolo3_vgg16 --anchors_path=configs/yolo3_anchors.txt --annotation_file=trainval_misaeng.txt --classes_path=configs/misaeng_classes.txt --eval_online --save_eval_checkpoint --val_annotation_file=test_misaeng.txt" this command, and it returns like this.

"ValueError: The name "predict_conv_1" is used 3 times in the model. All layer names should be unique."

How could i resolve it?

**Comment by david8862** [comment]
@yellowjs0304 it's a model definition bug for VGG16 backbone and I've commit a fix for that. Pls try the latest code. Sorry for trouble.

**Comment by yellowjs0304** [comment]
Thank u for fast reply~ i'll try it.
