### ISSUE TITLE
tensorflow.keras

### ISSUE THREAD

**Issue by ardeal** [david8862/keras-YOLOv3-model-set#12]
Hi,

I have installed tensorflow and keras by commands:
```Python
pip install tensorflow
pip install keras
```

however, in your code:
```Python
from tensorflow.keras import backend as K
```
tensorflow.keras is not installed.

how should I install tensorflow.keras?

Thanks,

**Comment by david8862** [comment]
> Hi,
> 
> I have installed tensorflow and keras by commands:
> 
> ```python
> pip install tensorflow
> pip install keras
> ```
> 
> however, in your code:
> 
> ```python
> from tensorflow.keras import backend as K
> ```
> 
> tensorflow.keras is not installed.
> 
> how should I install tensorflow.keras?
> 
> Thanks,

tensorflow.keras has been a submodule of tensorflow for recent release. So it should have been involved if tensorflow is ready.

**Comment by ardeal** [comment]
> 
> 
> > Hi,
> > I have installed tensorflow and keras by commands:
> > ```python
> > pip install tensorflow
> > pip install keras
> > ```
> > 
> > 
> > however, in your code:
> > ```python
> > from tensorflow.keras import backend as K
> > ```
> > 
> > 
> > tensorflow.keras is not installed.
> > how should I install tensorflow.keras?
> > Thanks,
> 
> tensorflow.keras has been a submodule of tensorflow for recent release. So it should have been involved if tensorflow is ready.

So, it might be that I should install a more recent version of tf. what is the tf version you are using?

Thanks,

**Comment by david8862** [comment]
> > > Hi,
> > > I have installed tensorflow and keras by commands:
> > > ```python
> > > pip install tensorflow
> > > pip install keras
> > > ```
> > > 
> > > 
> > > however, in your code:
> > > ```python
> > > from tensorflow.keras import backend as K
> > > ```
> > > 
> > > 
> > > tensorflow.keras is not installed.
> > > how should I install tensorflow.keras?
> > > Thanks,
> > 
> > 
> > tensorflow.keras has been a submodule of tensorflow for recent release. So it should have been involved if tensorflow is ready.
> 
> So, it might be that I should install a more recent version of tf. what is the tf version you are using?
> 
> Thanks,

tf 1.14.0 and later should be ok

**Comment by ardeal** [comment]
> tf 1.14.0 and later should be ok

**Comment by ardeal** [comment]
> 
> 
> > > > Hi,
> > > > I have installed tensorflow and keras by commands:
> > > > ```python
> > > > pip install tensorflow
> > > > pip install keras
> > > > ```
> > > > 
> > > > 
> > > > however, in your code:
> > > > ```python
> > > > from tensorflow.keras import backend as K
> > > > ```
> > > > 
> > > > 
> > > > tensorflow.keras is not installed.
> > > > how should I install tensorflow.keras?
> > > > Thanks,
> > > 
> > > 
> > > tensorflow.keras has been a submodule of tensorflow for recent release. So it should have been involved if tensorflow is ready.
> > 
> > 
> > So, it might be that I should install a more recent version of tf. what is the tf version you are using?
> > Thanks,
> 
> tf 1.14.0 and later should be ok



I am using tf 2.0.0, but I am still facing the issue when I tried to import tensorflow.keras. I saw the error hinting wave line under the syntax: from tensorflow.keras import backend as K.

in the following picture, you could see the red wave line under from tensorflow.keras import backend as K: 
![image](https://user-images.githubusercontent.com/6227348/71701478-8a1b1900-2e04-11ea-9eeb-ef0d347185d2.png)

However, the code could correctly be run. it is quite weird.

Anyway, thanks for your help. The code could be run now.
