### ISSUE TITLE
Can't use other backbones than Darknet

### ISSUE THREAD

**Issue by vse-motec** [david8862/keras-YOLOv3-model-set#121]
I managed to use yolo3 for inference using this command:
```
python yolo.py --model_type yolo3_darknet --anchors_path configs/yolo3_anchors.txt --weights_path weights/yolov3.h5 --image
```
It also works with yolo2 and yolo4 (provided that the arguments are adjusted and the corresponding weight files available).

However, these models all use the Darknet backbone (either Darknet53, CSPDarknet53 or Darknet19).
When I want to use a backbone that is not based on Darknet, e.g. the yolo3_mobilenet model with the following command

```
python yolo.py --model_type yolo3_mobilenet --anchors_path configs/yolo3_anchors.txt --weights_path weights/yolov3.h5 --image
```
the weights are not loaded correctly and an Error is displayed, e.g.:

> ValueError('You are trying to load a weight file containing 147 layers into a model with 97 layers.')

I am still able to pass an image for inference, but the results are totally useless. There are tons of boxes which belong to wrong classes and seem to have a uniform probability distribution.

Does anyone know how to use other backbones properly?

Thank you in advance

**Comment by david8862** [comment]
@vse-motec for other backbones you need to download & load corresponding pretrained weights for inference, e.g. [YOLOv3 Lite-Mobilenet](https://github.com/david8862/keras-YOLOv3-model-set/releases/download/v1.1.0/yolo3_mobilenet_lite_416_coco.tar.gz) for yolo3_mobilenet_lite, like

```
python yolo.py --model_type yolo3_mobilenet_lite --anchors_path configs/yolo3_anchors.txt --weights_path yolo3_mobilenet_lite_416_coco.h5 --image
```

**Comment by vse-motec** [comment]
@david8862 thank you for your reply. 

When inspecting the code I noticed that the backbone weights (e.g. for mobilenet) are taken from the provided Keras model. When using e.g. model_type yolo3_mobilenet, then the weights for mobilenet are actually automatically downloaded and loaded for the backbone network (this happens in yolo3/modles/yolo3_mobilenet.py, line 15).
Subsequently, the backbone is extended by the yolov3 head (line 34) and then the yolov3 weights (that I specified with the --weights_path argument) are loaded.

Judging from your answer, the automatically downloaded weights are useless. Instead, I need to download the proper weights from somewhere else (e.g. other repos as linked in the table below with sample evaluations).

Is this correct? If this is the case, then the above mentioned line 15 can be changed to have 
```
weights=None
```
to be passed to the created model to save time/disk space/bandwidth.

**Comment by david8862** [comment]
@vse-motec the backbone weights auto loaded from keras model are imagenet pretrained, which is for transfer training from imagenet, the common approach for detector train. But if you specify any third party pretrained detector model (e.g. pretrained on COCO or custom dataset) for train/inference, it will overwrite the auto-loaded backbone weights. But the model type should still be matched.

**Comment by vse-motec** [comment]
Thank you for the clarification. I guess, I am still missing something.
For instance, your example command
```
python yolo.py --model_type yolo3_mobilenet_lite --anchors_path configs/yolo3_anchors.txt --weights_path yolo3_mobilenet_lite_416_coco.h5 --image
```
works fine.

But using the Xception backbone does not work:

```
python yolo.py --model_type yolo3_xception --anchors_path configs/yolo3_anchors.txt --weights_path yolo3_xception_608_coco.h5 --image
```
The weights are from your release 1.1.0. I also tested

> yolo3_xception_512_voc.h5

from the relese 1.0.0

Both result in this error: 

> ValueError('Shapes (1, 1, 2048, 512) and (1024, 2048, 1, 1) are incompatible')

Did the model definition change in the meantime or am I still missing something?

**Comment by david8862** [comment]
@vse-motec  "yolo3_xception" pretrained weights is abandoned since its model structure has been changed in further commit, so pls ignore this error. I'll update related pretrained model later

**Comment by vse-motec** [comment]
@david8862 please notify me in this issue as soon as you release the modified model (no hurry). I will then close this issue.

**Comment by vse-motec** [comment]
I have been able to progress with the normal yolo3 model, no need for other models. I therefore close this issue.
