### ISSUE TITLE
Whats YOLO and YOLO_np inside yolo.py

### ISSUE THREAD

**Issue by sudo-install-MW** [david8862/keras-YOLOv3-model-set#125]
Hi @david8862 this is the finest implementation of a single-shot object detector with a lot of toolkits to tweak and optimize. It will be great if you can shed some light on the difference between the class YOLO and YOLO_np inside yolo.py.

Thanks
Mahesh

**Comment by david8862** [comment]
@sudo-install-MW  YOLO is a wrapper class which use tf.keras batch-wise layer for yolo prediction postprocess, while YOLO_np use a numpy implementation for that.

**Comment by sudo-install-MW** [comment]
Thanks for your quick response @david8862, now I am able to understand the difference in the post-processing pipeline of the two classes.
