### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by sudo-install-MW** [david8862/keras-YOLOv3-model-set#127]
Hi David, 
I am trying to train tiny-yolo3-mobilenet-lite using just the person class in the coco dataset. 
Every epoch is estimated to be 1 hour 30 minutes long. Its very slow and is there any tips and tricks you will share to speed up training?

 My training config is as follows:
```
--model_type=tiny_yolo3_mobilenet_lite
--model_image_size=320x320
--anchors_path=configs/tiny_yolo3_anchors.txt
--annotation_file=/train2017.txt
--val_annotation_file=/val2017.txt
--batch_size=2
--multiscale
--classes_path=/configs/coco_classes_custom.txt
--eval_online
--save_eval_checkpoint
--weights_path=/logs/000/ep001-loss16.432-val_loss29.379-mAP1.126.h5
```
I am also wondering Is it something to do with model.fit_generator() workers?

**Comment by david8862** [comment]
@sudo-install-MW  from the configuration, maybe you can try to enlarge batch size to get less steps for an epoch. "--batch_size=2" is usually too small for detector training

**Comment by sudo-install-MW** [comment]
Thanks for your quick response @david8862. Training time reduced after I increased the batch_size. Is it possible for you to share the training config you used to create trained models that are shared in the repository? 

It will be great to help me train the model in the parameters you have used to get the best result possible. It will also clear some of my questions like did you use multiscale training, mosaic augmentation, etc

**Comment by david8862** [comment]
@sudo-install-MW generally you can start with following reference training config:

```
# python train.py --model_type=<selected type>
                             --anchors_path=<selected anchors>
                             --annotation_file=<your dataset file>
                             --classes_path=<your class label>
                             --batch_size=16
                             --optimizer=adam
                             --learning_rate=0.001
                             --decay_type=cosine
                             --transfer_epoch=10
                             --eval_online
                             --save_eval_checkpoint
```

some enhanced training trick like "multiscale training" or "mosaic augmentation" may not fit for every kind of dataset. You can try them more after getting a reasonable result.

**Comment by sudo-install-MW** [comment]
Thanks for your prompt response @david8862
