### ISSUE TITLE
Not able to get the correct result (local variable 'yolo_model' referenced before assignment)

### ISSUE THREAD

**Issue by govindamagrawal** [david8862/keras-YOLOv3-model-set#13]
Hi David,
I am using the pre-trained files provided by you to get the results, but somehow I am getting random results and error. I want to evaluate on Tiny YOLOv3 Lite-Mobilenet which has inference time of 11ns as mentioned. I am using the following commad:

python yolo.py --model_type=tiny_yolo3_mobilenet_lite --weights_path=/home/govindam/Downloads/tiny_yolo3_mobilnet_lite_416_voc.h5 --anchors_path=configs/yolo3_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --image

But I am getting the following error:
Traceback (most recent call last):
  File "yolo.py", line 404, in <module>
    yolo = YOLO_np(**vars(args))
  File "yolo.py", line 63, in __init__
    self.yolo_model = self._generate_model()
  File "yolo.py", line 90, in _generate_model
    assert yolo_model.layers[-1].output_shape[-1] == \
UnboundLocalError: local variable 'yolo_model' referenced before assignment

Can you please help me with evaluting the different weight files as trained by you. Also, can you help me retraing the tiny yolo mobilenet network only for persons category as persons is only concern for me right now, with least inference time.

**Comment by david8862** [comment]
> category

Hi, govindamagrawal. For "tiny_yolo3_mobilenet_lite" model, you need to use Tiny YOLOv3 anchors definition when loading the pretrained weights, like:
'''
python yolo.py --model_type=tiny_yolo3_mobilenet_lite --weights_path=/home/govindam/Downloads/tiny_yolo3_mobilnet_lite_416_voc.h5 --anchors_path=configs/tiny_yolo3_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --image
'''

To retrain the model with your special category & datasets, you can create your class definition config file "person.txt" and generate your data annotation as [train](https://github.com/david8862/keras-YOLOv3-model-set#train) part. Then launch your training like:

'''
python train.py --model_type=tiny_yolo3_mobilenet_lite --anchors_path=configs/tiny_yolo3_anchors.txt --annotation_file=<your annotation file> --classes_path=configs/person.txt --eval_online --save_eval_checkpoint
'''

It's just a reference training config. You can adjust according to your train process

**Comment by david8862** [comment]
> Hi David,
> I am using the pre-trained files provided by you to get the results, but somehow I am getting random results and error. I want to evaluate on Tiny YOLOv3 Lite-Mobilenet which has inference time of 11ns as mentioned. I am using the following commad:
> 
> python yolo.py --model_type=tiny_yolo3_mobilenet_lite --weights_path=/home/govindam/Downloads/tiny_yolo3_mobilnet_lite_416_voc.h5 --anchors_path=configs/yolo3_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --image
> 
> But I am getting the following error:
> Traceback (most recent call last):
> File "yolo.py", line 404, in
> yolo = YOLO_np(**vars(args))
> File "yolo.py", line 63, in **init**
> self.yolo_model = self._generate_model()
> File "yolo.py", line 90, in _generate_model
> assert yolo_model.layers[-1].output_shape[-1] ==
> UnboundLocalError: local variable 'yolo_model' referenced before assignment
> 
> Can you please help me with evaluting the different weight files as trained by you. Also, can you help me retraing the tiny yolo mobilenet network only for persons category as persons is only concern for me right now, with least inference time.

Hi, @govindamagrawal.
For "tiny_yolo3_mobilenet_lite" model, you need to use Tiny YOLOv3 anchors definition when loading the pretrained weights, like:
```
# python yolo.py --model_type=tiny_yolo3_mobilenet_lite --weights_path=/home/govindam/Downloads/tiny_yolo3_mobilnet_lite_416_voc.h5 --anchors_path=configs/tiny_yolo3_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --image
```

To retrain the model with your special category & datasets, you can create your class definition config file "person.txt" and generate your data annotation as [train](https://github.com/david8862/keras-YOLOv3-model-set#train) part. Then launch your training like:

```
# python train.py --model_type=tiny_yolo3_mobilenet_lite --anchors_path=configs/tiny_yolo3_anchors.txt --annotation_file=<your annotation file> --classes_path=configs/person.txt --eval_online --save_eval_checkpoint
```

It's just a reference training config. You can adjust according to your train process

**Comment by govindamagrawal** [comment]
Thanks a lot David for the reply :)

**Comment by bessszilard** [comment]
I am executing this command, and got the same `UnboundLocalError: local variable 'yolo_model' referenced before assignment` error. What causes the problem?

```
!python yolo.py --model_type=yolo3_darknet \
--weights_path=/content/weights/yolov3.h5 \
--anchors_path=configs/tiny_yolo3_anchors.txt --classes_path=/content/voc-bosch.names \
--model_image_size=416x416 --image --input /content/17174.png
```

**Comment by david8862** [comment]
> yolo3_anchors.txt

Hi @bessszilard, sorry for missing your questions. For using yolo3_darknet model type you need to assign "config/yolo3_anchors.txt" as its anchor file.
