### ISSUE TITLE
Inference on custom yolo v4 tiny model

### ISSUE THREAD

**Issue by samhank** [david8862/keras-YOLOv3-model-set#130]
I have already trained a custom version of Yolo v4 tiny model using the darknet. The conversion of  the darknet model to the Keras model works without issues. But there is an issue is in testing the model (I don't want to train the model).

Can you please tell me what should be the  --model_type in command if I am using a custom version of Yolov4 tiny. 

Do I need to make any further changes to the code?

**Comment by david8862** [comment]
@samhank for the darknet converted model, you can use [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py) to test it

**Comment by samhank** [comment]
Thank you for your response
