### ISSUE TITLE
Add support for converting to SavedModel

### ISSUE THREAD

**Issue by IRDonch** [david8862/keras-YOLOv3-model-set#131]
The `tools/model_converter/convert.py` script ought to be able to save the model in the SavedModel format. It can pretty much do that already if you remove [this assertion](https://github.com/david8862/keras-YOLOv3-model-set/blob/1f97139/tools/model_converter/convert.py#L89), but it would be nice if it could do that unmodified.

**Comment by david8862** [comment]
@IRDonch sure, done

**Comment by IRDonch** [comment]
OK, thank you!
