### ISSUE TITLE
Success of running on android?

### ISSUE THREAD

**Issue by Maxwell2Gyamfi** [david8862/keras-YOLOv3-model-set#142]
Converted yolov4 to keras using this repo
Then converted keras to tfite using official tensorflow lite converter as tf2 not supported.
Now when i run on android it crashes immediately.

Anyone had any luck?
And lastly how do you perform inference using keras model and tflite model of yolov4?
Thank you

**Comment by david8862** [comment]
@Maxwell2Gyamfi you can try [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py) to run inference for keras/tflite model
