### ISSUE TITLE
Pillow Or Opencv

### ISSUE THREAD

**Issue by guishilike** [david8862/keras-YOLOv3-model-set#144]
pillowo和pencv在resize 插值方式略有不同，导致结果可能有细微差异，但对模型影响似乎没有定性分析，从很多人观点来看似乎pillow效果好一些，但我也看过有在pytorch中使用opencv实现yolo的数据增强，采用opencv能够提高速度，本身算法也讲究一个tradeoff,这两者哪个相对好一些？

**Comment by david8862** [comment]
@guishilike 我没有专门比较过Pillow和OpenCV的图像处理方式对模型训练的影响。原则上只要同一模型的训练和推理时使用的方式一致应该就不会有什么差别。使用OpenCV的一个优点是比较容易和模型推理部署的C++环境统一。

**Comment by guishilike** [comment]
我试验了一下，pillow和cv2插值公式存在些许差异，pillow在缩小尺度大于2的情况下差距不大，而cv2不同的interpolation效果明显不同，似乎只有cv2.INTER_AREA效果好一些（yolov5中缩小采用的便是 cv2.INTER_AREA， 除非数据增强才可能采用cv2.INTER_LINEAR）。
