### ISSUE TITLE
multi label - file annotation format

### ISSUE THREAD

**Issue by MrSouwbauck** [david8862/keras-YOLOv3-model-set#146]
I can't find the file annotation format for multi label classification.
I guess you just need to duplicate boxes coordinates for each class id, like :

image/path xmin xmax ymin ymax id1 xmin xmax ymin ymax id2 ..

I want to be sure before coding the data converter.
thanks in advance !

**Comment by MrSouwbauck** [comment]
furthermore, is there a way to connect multiple detection when using multiclass ? I want to draw anchors once with all related class names attached. If it's not implemented yet, i'll try to do it. It should not be too hard since IoU function already implemented.

**Comment by david8862** [comment]
@MrSouwbauck  currently this repo doesn't provide multi label capability for one bbox. You can try to use duplicated if it's OK for you

**Comment by MrSouwbauck** [comment]
@david8862 okay, thanks for the quick response !
