### ISSUE TITLE
Drop of the AP after --dump_model

### ISSUE THREAD

**Issue by negvet** [david8862/keras-YOLOv3-model-set#147]
Hi!

I am running [d38c3d865f](https://github.com/david8862/keras-YOLOv3-model-set/tree/d38c3d865f7190ee9b19a30e91f2b750a31320c1)
I downloaded the weights and converted them to `weights/yolov4.h5` and `weights/cspdarknet53.h5` according to Quick Start.

Inference works fine.
Then I evaluateed the `weights/yolov4.h5`, without training:

`python eval.py --model_path=weights/yolov4.h5 --anchors_path=configs/yolo4_anchors.txt --classes_path=configs/coco2017_origin_classes.txt --model_image_size=608x608 --eval_type=COCO --iou_threshold=0.5 --conf_threshold=0.001 --annotation_file=val2017.txt --save_result`

The result: 
![image](https://user-images.githubusercontent.com/17028475/107034364-a89dd180-67c7-11eb-8015-b7a0cb5ac3ac.png)

Looks good.

I want to test the tuning of YOLOv4 using the COCO dataset. The problem is that, I am not able to start from the `weights/yolov4.h5`:

`python train.py --model_type=yolo4_darknet --anchors_path=configs/yolo4_anchors.txt --annotation_file=train2017.txt --val_annotation_file=val2017.txt --classes_path=configs/coco2017_origin_classes.txt --save_eval_checkpoint --model_image_size=608x608 --learning_rate 0.00001 --weights_path=weights/yolov4.h5 --transfer_epoch=0 --total_epoch=1`

because of name mismatch (the model is redefined, outputs are renamed, then starting from `conv2d_93` layers have different names):

```
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    main(args)
  File "train.py", line 150, in main
    model = get_train_model(args.model_type, anchors, num_classes, weights_path=args.weights_path, freeze_level=freeze_level, optimizer=optimizer, label_smoothing=args.label_smoothing, elim_grid_sense=args.elim_grid_sense, model_pruning=args.model_pruning, pruning_end_step=pruning_end_step)
  File "/home/negvet/keras-YOLOv3-model-set/yolo3/model.py", line 243, in get_yolo3_train_model
    model_body.load_weights(weights_path, by_name=True)#, skip_mismatch=True)
  File "/home/negvet/yolo_venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2209, in load_weights
    f, self.layers, skip_mismatch=skip_mismatch)
  File "/home/negvet/yolo_venv/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 786, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #319 (named "conv2d_94"), weight <tf.Variable 'conv2d_94/kernel:0' shape=(1, 1, 512, 256) dtype=float32, numpy=
array([[[[ 0.06010031, -0.02608135,  0.03438468, ..., -0.02796663,
          -0.01654074,  0.07196554],
         [ 0.06237837,  0.00792135,  0.07800164, ...,  0.03070227,
          -0.04063595, -0.00674969],
         [ 0.05886016,  0.08145585,  0.0854909 , ...,  0.07558893,
           0.080747  , -0.00712469],
         ...,
         [ 0.02122958,  0.05400904,  0.00345819, ...,  0.08074024,
           0.03620414, -0.05979896],
         [-0.07532272, -0.02289718, -0.05862878, ...,  0.06100825,
          -0.08570147, -0.07524633],
         [ 0.009951  , -0.01178542,  0.02151559, ...,  0.08526137,
           0.00151183,  0.03465303]]]], dtype=float32)> has shape (1, 1, 512, 256), but the saved weight has shape (256, 128, 3, 3).
```

I can start tuning only if I first dump the `weights/yolov4.h5`.

Now, if I run

`python yolo.py --model_type=yolo4_darknet --weights_path=weights/yolov4.h5 --anchors_path=configs/yolo4_anchors.txt --classes_path=configs/coco2017_origin_classes.txt --model_image_size=608x608 --output_model_file=yolov4-dumped.h5 --dump_model`

And then again eval of the resulting `yolov4-dumped.h5` model. The result:
![image](https://user-images.githubusercontent.com/17028475/107034316-9885f200-67c7-11eb-8616-873a44289b48.png)

I understand that `--dump_model` suppose to convert the model from train to eval mode. But the metrics should not drop because I dump the `weights/yolov4.h5`, right?

Question: why do the metrics drop?

Best

**Comment by negvet** [comment]
To load `weights/yolov4.h5` for the `train.py` script, its is required to remove `by_name=True` from this [line](https://github.com/david8862/keras-YOLOv3-model-set/blob/391e90c6e58e31eeaa78c348af716e9a37901d48/yolo3/model.py#L240).

But the metric does not recover anyway, with tuning I am just approaching COCO AP = 44.59%, not 47.32%.

**Comment by david8862** [comment]
@negvet  have you tried the latest code? I've verified and the dump model make same mAP with converted one on latest.

**Comment by negvet** [comment]
@david8862, great, the latest code works.
Thanks a lot!
