### ISSUE TITLE
IndexError: index 19 is out of bounds for axis 1 with size 19

### ISSUE THREAD

**Issue by negvet** [david8862/keras-YOLOv3-model-set#148]
After yesturday [commit](https://github.com/david8862/keras-YOLOv3-model-set/commit/5409471bc6599068424dba000db747d9ef3208d6), `train.py` fails with the following error:

```
  File "/home/negvet/keras-YOLOv3-model-set/yolo3/data.py", line 274, in yolo3_data_generator
    y_true = preprocess_true_boxes(box_data, input_shape, anchors, num_classes, multi_anchor_assign)

  File "/home/negvet/keras-YOLOv3-model-set/yolo3/data.py", line 175, in preprocess_true_boxes
    y_true[l][b, j, i, k, 0:4] = true_boxes[b,t, 0:4]

IndexError: index 19 is out of bounds for axis 1 with size 19
```

If I switch back to [8795](https://github.com/david8862/keras-YOLOv3-model-set/tree/87952c23a75ae2fc7c2cb04a3f4494cc75c2f97c) - the error disappears.

**Comment by david8862** [comment]
@negvet it's a bug in new rotate data augment and I've just commit fix for it. You can try again now.

**Comment by negvet** [comment]
The fix works, thanks!
