### ISSUE TITLE
YOLOv4 Efficientnet(B1): AP drop and tuning

### ISSUE THREAD

**Issue by negvet** [david8862/keras-YOLOv3-model-set#150]
Hi @david8862 

Now I have the same issue as in [147](https://github.com/david8862/keras-YOLOv3-model-set/issues/147) but with YOLOv4 Efficientnet(B1). 

You reporting 82.39% on the PascalVOC dataset.
After downloading and evaluation of the model with

`python eval.py --anchors_path=configs/yolo4_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=512x512 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.001 --annotation_file=data/PascalVOC/2007_test.txt --save_result --model_path=weights/yolo4_efficientnet_512_voc.h5`

I can get 82.22%, which is close but not exactly. Not a big thing.

Then I want to tune the YOLOv4 Efficientnet(B1) on the PascalVOC dataset. Before that I do `dump` 

`python yolo.py --model_type=yolo4_efficientnet --anchors_path=configs/yolo4_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=512x512 --dump_model --weights_path=weights/yolo4_efficientnet_512_voc.h5 --output_model_file=yolo4-efficientnet-dumped.h5`

and `eval`

`python eval.py --anchors_path=configs/yolo4_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=512x512 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.001 --annotation_file=data/PascalVOC/2007_test.txt --save_result --model_path=yolo4-efficientnet-dumped.h5`

The result is 73.56%, which is a significant drop. Looks like a bug.

Could you also please share the training strategy for YOLOv4 Efficientnet(B1) which helped you to get 82.39%?

Best

**Comment by david8862** [comment]
@negvet I think the mAP drop on dumped model should be caused by a SPP block change, which is mentioned at #132 (in Chinese). When I release the 82.39% model I'm still using the old SPP block strucure.

**Comment by negvet** [comment]
@david8862 I see, I was able to reproduce 82.39% with [d580082](https://github.com/david8862/keras-YOLOv3-model-set/tree/d5800824a50b09ddb74feee45418dff8c06cdc79) on the dumped model.

do you have any plans to update the 82.39% metric in the table?

**Comment by david8862** [comment]
@negvet  thanks. I may try to retrain the yolo4_efficientnet model and update the release link later if have bandwidth
