### ISSUE TITLE
GridMask support

### ISSUE THREAD

**Issue by negvet** [david8862/keras-YOLOv3-model-set#154]
After GridMask data augmentation support [436826a](https://github.com/david8862/keras-YOLOv3-model-set/commit/436826ae035b7ea32ebd019c0fbf2c12c6605307), sooner or later (within the first epoch) the following error rises during training:

```
File "/my_dir/keras-YOLOv3-model-set/yolo3/data.py", line 89, in get_ground_truth_data
    box_data[:len(boxes)] = boxes
ValueError: could not broadcast input array from shape (1,0) into shape (1,5)
```
Some box has a shape (1,0).

Looks like an issue with the `random_gridmask` method. 
After commenting out `image, boxes = random_gridmask(image, boxes)` it started to work.

Dataset: COCO
Model: yolo4_darknet

Please check it out.

**Comment by david8862** [comment]
@negvet a corner case bug for GridMask augment and I've just commit fix for that. Many thanks for feedback~
