### ISSUE TITLE
saved_model

### ISSUE THREAD

**Issue by guishilike** [david8862/keras-YOLOv3-model-set#155]
模型可以保存为saved_model并调用吗

**Comment by david8862** [comment]
@guishilike 目前没有支持相应的功能，不过应该可以在tf.keras模型保存和载入部分做简单的修改实现

**Comment by guishilike** [comment]
那用tf2的权重，可以转成bp文件，做推理使用吗

**Comment by david8862** [comment]
> 那用tf2的权重，可以转成bp文件，做推理使用吗

@guishilike 可以参考README中的[tensorflow-model-convert](https://github.com/david8862/keras-YOLOv3-model-set#tensorflow-model-convert)，在TF1环境下用脚本工具进行转换。一般都是可以的

**Comment by guishilike** [comment]
做推理，c和python 差距大吗

**Comment by david8862** [comment]
精度基本是一样的，速度则取决于具体的部署环境了

**Comment by guishilike** [comment]
我想问一下h5转换的模型是包括loss层的吗，这种自定义的层似乎转换不了

**Comment by david8862** [comment]
> 我想问一下h5转换的模型是包括loss层的吗，这种自定义的层似乎转换不了

模型转换需要先按照[Model dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump)部分的描述，将训练模型导出为推理模型(去除loss层)后才可以进行

**Comment by guishilike** [comment]
我尝试了一下saved_model 格式，可以加载，C++也可以调用。并将yolo的decode部分写入自定义Layer一起保存到了saved_model中（Lambda层中有python的静态函数导致直接转会失败），现在可以直接返回所要结果。

**Comment by david8862** [comment]
> 我尝试了一下saved_model 格式，可以加载，C++也可以调用。并将yolo的decode部分写入自定义Layer一起保存到了saved_model中（Lambda层中有python的静态函数导致直接转会失败），现在可以直接返回所要结果。

good, thanks. saved model因为是TF原生的模型格式，比较容易支持postprocess中较复杂的op
