### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__array_interface__'

### ISSUE THREAD

**Issue by seunghalee1226** [david8862/keras-YOLOv3-model-set#159]
I always got **AttributeError: 'NoneType' object has no attribute '__array_interface__'**

I think, it is better to fix some code in yolo.py.

from video_FourCC = cv2.VideoWriter_fourcc(*'XVID') 
to video_FourCC = cv2.VideoWriter_fourcc(*'mp4v')

after fix it, it works well.

**Comment by david8862** [comment]
@seunghalee1226 have fixed
