### ISSUE TITLE
GPU usage and batch size

### ISSUE THREAD

**Issue by gillmac13** [david8862/keras-YOLOv3-model-set#16]
Hi David,

I now have explored your repo, which is very interesting because of your dissociation of yolo layers logic and backbones !
I have no usage problem except that I find my gpu memory load not decreasing with the batch size as would be expected (I am running on a GTX 1070). The memory when idle is 280 KB but when training:
- if the batch size is 16, the memory load is 7.9 MB, dangerously close to my limit of 8.1 MB
- if the batch size is 8 or 4, I get the same result.
While my various training attempts have not crashed at this point, would you have an explanation ?
Thanks in advance
Gilles

**Comment by david8862** [comment]
> Hi David,
> 
> I now have explored your repo, which is very interesting because of your dissociation of yolo layers logic and backbones !
> I have no usage problem except that I find my gpu memory load not decreasing with the batch size as would be expected (I am running on a GTX 1070). The memory when idle is 280 KB but when training:
> 
> * if the batch size is 16, the memory load is 7.9 MB, dangerously close to my limit of 8.1 MB
> * if the batch size is 8 or 4, I get the same result.
>   While my various training attempts have not crashed at this point, would you have an explanation ?
>   Thanks in advance
>   Gilles

many thanks. What's your training env & config cmd? I've tried to enable dynamic alloc GPU resource [here](https://github.com/david8862/tf-keras-stacked-hourglass-keypoint-detection/blob/master/common/utils.py#L12), but that may still rely on the TF environment (TF version, CUDA/CuDNN version, etc.)

**Comment by gillmac13** [comment]
Thanks for your prompt reply!

Here is an example of cmd line (they all behave the same):
$ python3 train.py --model_type yolo3_nano  --annotation_file train.txt --val_annotation_file valid.txt --classes_path configs/my_yolo_class.txt --anchors_path=configs/yolo3_anchors.txt --total_epoch 30 --save_eval_checkpoint --freeze_level 0 --batch_size 16

I am training from my own dataset from scratch, with 1 class. The enviromnent is TF2.1, cuda version 10.1.

I may have a hint to an explanation though... When I start training, I get these warning/error lines:

`Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10000 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-02-03 14:41:55.952071: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 9.77G (10485760000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-02-03 14:41:55.952675: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 8.79G (9437184000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2020-02-03 14:41:55.953257: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 7.91G (8493465600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Create  YOLOv3 yolo3_nano model with 9 anchors and 1 classes.
`

It looks like tensorflow is first trying to allocate 10 MB to the process, finds it cannot do it, and reduces the allocation iteratively until it fits. 
As for why the memory load is always the same: possibly because the process "accumulates" batches until the memory is filled to the hilt, for efficiency purposes. The batches are then processed sequentially as intended.
Just to prove this, I increased the batch size to 32, and I got a CUDA memory crash at the point where data is loaded.
So maybe the symptoms in my first comment are benign and I should find a way to NOT have tensorflow try to allocate more then e.g. 7MB. Or I'm totally wrong!

Gilles

**Comment by david8862** [comment]
> Thanks for your prompt reply!
> 
> Here is an example of cmd line (they all behave the same):
> $ python3 train.py --model_type yolo3_nano --annotation_file train.txt --val_annotation_file valid.txt --classes_path configs/my_yolo_class.txt --anchors_path=configs/yolo3_anchors.txt --total_epoch 30 --save_eval_checkpoint --freeze_level 0 --batch_size 16
> 
> I am training from my own dataset from scratch, with 1 class. The enviromnent is TF2.1, cuda version 10.1.
> 
> I may have a hint to an explanation though... When I start training, I get these warning/error lines:
> 
> `Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10000 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1) 2020-02-03 14:41:55.952071: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 9.77G (10485760000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory 2020-02-03 14:41:55.952675: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 8.79G (9437184000 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory 2020-02-03 14:41:55.953257: I tensorflow/stream_executor/cuda/cuda_driver.cc:801] failed to allocate 7.91G (8493465600 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory Create YOLOv3 yolo3_nano model with 9 anchors and 1 classes. `
> 
> It looks like tensorflow is first trying to allocate 10 MB to the process, finds it cannot do it, and reduces the allocation iteratively until it fits.
> As for why the memory load is always the same: possibly because the process "accumulates" batches until the memory is filled to the hilt, for efficiency purposes. The batches are then processed sequentially as intended.
> Just to prove this, I increased the batch size to 32, and I got a CUDA memory crash at the point where data is loaded.
> So maybe the symptoms in my first comment are benign and I should find a way to NOT have tensorflow try to allocate more then e.g. 7MB. Or I'm totally wrong!
> 
> Gilles

Got your idea. Then you can try to change the "memory_limit" config for TF 2.x in [optimize_tf_gpu](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/common/utils.py#L20) and uncomment the "set_memory_growth" config for the TF 2.x dynamic GPU alloc

**Comment by gillmac13** [comment]
Thanks a lot! It works like a charm.
This issue can be closed.
