### ISSUE TITLE
Regularizer

### ISSUE THREAD

**Issue by guishilike** [david8862/keras-YOLOv3-model-set#160]
我想问一下，Conv2D的kernel_regularizer和bias_regularizer为什么设置成1e-5，我看其他yolo似乎没有设置

**Comment by david8862** [comment]
这里是为了对应PyTorch或Darknet框架中的weight decay约束，原始值应该是5e-4。但由于tf.keras下的regularizer与weight decay的原理有一些差别，所以实验性的取了一个较小的值。实际训练时可以考虑作为超参进行调整
