### ISSUE TITLE
Dumping inference model

### ISSUE THREAD

**Issue by casbolwerk** [david8862/keras-YOLOv3-model-set#163]
Hi David,

For inference using TensorRT I was using your repo to dump my model and convert it to ONNX. I had a question regarding the dumping process and the last layers of the model requiring postprocessing. I am training YOLOv4 mobilenet right now, but this question is more of a general one.

So in the yolo.py file there are two classes for dumping, YOLO and YOLO_np. A YOLO inference model outputs classes, boxes and scores directly without needing postprocessing. YOLO_np's inference model does need postprocessing. The `get_yolo3_inference_model` function that YOLO uses still uses the same `get_yolo3_model` function that YOLO_np immediately uses to dump. I would prefer to have the YOLO type of inference model that doesn't need postprocessing, but right now it uses YOLO_np by default. So my question is, what's the difference between YOLO and YOLO_np and can I just use YOLO to dump my training model or do I need to do something else.

```
boxes, scores, classes = Lambda(batched_yolo3_postprocess, name='yolo3_postprocess',
            arguments={'anchors': anchors, 'num_classes': num_classes, 'confidence': confidence, 'elim_grid_sense': elim_grid_sense})(
        [*model_body.output, image_shape])
    model = Model([model_body.input, image_shape], [boxes, scores, classes])
```
If by adding this I could just have an inference model that doesn't need postprocessing, I would much prefer that. Sadly, when dumping to a YOLO inference model, the `batched_yolo3_postprocess` has a call to `batched_yolo3_boxes_and_scores` that can't be found by the inference model while it is defined (probably not referenced in the h5 file).

Thanks!

**Comment by casbolwerk** [comment]
The conclusion for now is that I cannot directly use YOLO, because inference doesn't work afterwards. E.g. when calling eval.py after dumping using YOLO, the reference to `batched_yolo3_boxes_and_scores` (from postprocess.py) stored in `batched_yolo3_postprocess` is not recognized anymore. I'm not sure if it's worth importing `batched_yolo3_boxes_and_scores` somewhere where the reference is called or if it's better to write a function similar to `batched_yolo3_postprocess` for YOLO_np.

**Comment by david8862** [comment]
@casbolwerk  due to having some complex TF ops in postprocess layer, the YOLO inference model is just for tf/tf.keras inference usage, but not for converting to other framework. So if you're trying to do inference with ONNX/TensorRT, you may still need to use the no postprocessing model
