### ISSUE TITLE
get_yolo3_model() keeps looking for 'weights/darknet53.h5' even though I set weights_path=weights/yolov3.h5

### ISSUE THREAD

**Issue by chulminkw** [david8862/keras-YOLOv3-model-set#165]
Hello and thanks for this great project. This helps me a lot for YOLO.

When I 'm using yolo.py and train.py. it gives me error message 
OSError: Unable to open file (unable to open file: name = 'weights/darknet53.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I set default_config in yolo.py after I converted yolov3.weights to yolov3.h5 by using
python tools/model_converter/convert.py cfg/yolov3.cfg weights/yolov3.weights weights/yolov3.h5

default_config = {
        "model_type": 'yolo3_darknet',
        "weights_path": os.path.join('weights', 'yolov3.h5'),
        "pruning_model": False,
        "anchors_path": os.path.join('configs', 'yolo3_anchors.txt'),
        "classes_path": os.path.join('configs', 'coco_classes.txt'),
        "score" : 0.1,
        "iou" : 0.4,
        "model_image_size" : (416, 416),
        "elim_grid_sense": False,
        "gpu_num" : 1,
    }

It seems like get_yolo3_model() function in keras-YOLOv3-model-set\yolo3\model.py keeps using internal weights_path weights/darknet53.h5 in yolo3_model_map dictionary. 

How can I resolve this?

**Comment by david8862** [comment]
@chulminkw  that is auto backbone pretrained weights loading defined [here](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/yolo3/model.py#L76). You can comment it out if no need

**Comment by chulminkw** [comment]
Thanks, david8862 

So should I change yolo3_model_map dict from 
'yolo3_darknet': [yolo3_body, 185, 'weights/darknet53.h5'] 
to ['yolo3_darknet': [yolo3_body, 185, None]
in model.py ?

**Comment by david8862** [comment]
> Thanks, david8862
> 
> So should I change yolo3_model_map dict from
> 'yolo3_darknet': [yolo3_body, 185, 'weights/darknet53.h5']
> to ['yolo3_darknet': [yolo3_body, 185, None]
> in model.py ?

yes, correct

**Comment by chulminkw** [comment]
Thanks a lot.

**Comment by chulminkw** [comment]
Hello, 

it seems like yolo3.model.py is only taking darknet-body weight such as darknet53.h5 converted from darknet53.conv.74.weights. But I would like to take yolo-body weight such as yolov3.h5 converted from yolov3.weights

I tested this with model_type='yolo3_darknet'            

In line 202~203 from yolo3.model.py

if weights_path:
                model_body = model_function(input_tensor, num_anchors//3, num_classes, weights_path=weights_path)

and yolo3_body() in yolo3.models.yolo3_darknet.py, it is taking darknet_body weights. 

darknet = Model(inputs, darknet53_body(inputs))
if weights_path is not None:
    darknet.load_weights(weights_path, by_name=True)
    print('Load weights {}.'.format(weights_path))

Is there anyway to take yolo-body weights? I thought It would be nice to have both darknet-body weights and yolo-body weights
