### ISSUE TITLE
请问做inference时候使用diou或者iou是否和训练的时候的loss有关系？

### ISSUE THREAD

**Issue by ShihuaiXu** [david8862/keras-YOLOv3-model-set#187]
Hi, David, 我发现你在keras-YOLOv3-model-set-master\common\yolo_postprocess_np.py推理过程中默认使用了diou
if use_diou:
      iou = box_diou(b_nms)
但是我发现我在训练时没有用到diou，请问这样是合理的吗，还是说diou要和loss函数有关系？

**Comment by david8862** [comment]
@ShihuaiXu  在DIOU原作论文中，DIOU loss和DIOU NMS是作为两个相对独立的trick被提出的，因而在使用上应该也可以互相独立应用

**Comment by ShihuaiXu** [comment]
感谢您的回复，我理解了
