### ISSUE TITLE
ModuleNotFoundError: No module named 'imgaug'

### ISSUE THREAD

**Issue by daniele-salerno** [david8862/keras-YOLOv3-model-set#189]
I'm trying to convert an .h5 model to a tflite in this way:
python3.6 tools/model_converter/post_train_quant_convert.py --keras_model_file="weights/yolov4-tiny.h5" --annotation_file=classes.txt --model_input_shape=416x416 --sample_num=30 --output_file=model_quant.tflite 

This is the error and of course i have installed the imgaug package:
Traceback (most recent call last):
  File "tools/model_converter/post_train_quant_convert.py", line 14, in <module>
    from yolo3.data import get_ground_truth_data
  File "/home/dani/Projects/keras-YOLOv3-model-set/tools/model_converter/../../yolo3/data.py", line 8, in <module>
    from common.data_utils import normalize_image, letterbox_resize, random_resize_crop_pad, reshape_boxes, random_hsv_distort, random_horizontal_flip, random_vertical_flip, random_grayscale, random_brightness, random_chroma, random_contrast, random_sharpness, random_blur, random_motion_blur, random_rotate, random_gridmask, random_mosaic_augment, random_mosaic_augment_v5
  File "/home/dani/Projects/keras-YOLOv3-model-set/tools/model_converter/../../common/data_utils.py", line 9, in <module>
    import imgaug.augmenters as iaa
ModuleNotFoundError: No module named 'imgaug'

What i'm missing?

**Comment by david8862** [comment]
similiar issue at https://github.com/matterport/Mask_RCNN/issues/632. Maybe you can try `pip3 install git+https://github.com/aleju/imgaug`
