### ISSUE TITLE
请问anchor需要做resize吗

### ISSUE THREAD

**Issue by ShihuaiXu** [david8862/keras-YOLOv3-model-set#195]
thanks for your job，我的kmeans算法是基于原图尺寸（1280*800）的目标bbox计算anchor的，但是我在图像预处理时把图像resize到了352*224，请问david，那我要把之前anchor的宽除以（800/224），高除以（1280/352)吗？Thanks in advance

**Comment by david8862** [comment]
@ShihuaiXu  我的理解是不需要。因为YOLO在bbox wh部分的预测形式是直接以anchor为基准，得到原始bbox的长宽，而与模型输入尺寸无关:
```
exp(pred_w) * anchor_w = true_w
exp(pred_h) * anchor_h = true_h
```

如下图所示

![YOLOv3_bbox_predict](https://user-images.githubusercontent.com/25219223/127342824-63fd4243-cf4b-4771-83af-aa50e65a402b.png)

**Comment by ShihuaiXu** [comment]
非常感谢david，我再理解一下
