### ISSUE TITLE
YOLO fastest model_type

### ISSUE THREAD

**Issue by rzese** [david8862/keras-YOLOv3-model-set#197]
Hi all, which value should I set for the model_type argument to use YOLO fastest models?
I cannot find it.

Many thanks.

**Comment by david8862** [comment]
@rzese This repo didn't implement train/eval process for YOLO fastest model, so there's no corresponding model_type for it. But you can use [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py) to run inference with the converted model file.

**Comment by rzese** [comment]
Thank you for your kind reply.

I considered Yolo-Fastest because it is very small compared with the others and it can be used on an FPGA.
I need to start from a pre-trained network to do transfer learning on a different dataset. Have you any suggestions for me?

Many thanks again

**Comment by david8862** [comment]
For training Yolo-Fastest you may need to use its [original repo](https://github.com/dog-qiuqiu/Yolo-Fastest), or try to check some other light-weight model type here to see if anyone can match your requirement.

**Comment by rzese** [comment]
Thank you for your help.
