### ISSUE TITLE
ValueError: Cannot reshape array of size 43095 into shape (1.507,25) while evaluating

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [david8862/keras-YOLOv3-model-set#2]
I gave the following command 
`python eval.py --model_path=./weights/yolov3-tiny.h5 --anchors_path=configs/tiny_yolo_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.001 --annotation_file=annotations.txt --save_result`

This is the error I got
```
Traceback (most recent call last):
  File "eval.py", line 932, in <module>
    main()
  File "eval.py", line 928, in main
    eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
  File "eval.py", line 863, in eval_AP
    pred_classes_records = get_prediction_class_records(model_path, annotation_records, anchors, class_names, model_image_size, conf_threshold, save_result)
  File "eval.py", line 168, in get_prediction_class_records
    pred_boxes, pred_classes, pred_scores = yolo3_postprocess_np(model.predict([image_data]), image_shape, anchors, len(class_names), model_image_size, max_boxes=100, confidence=conf_threshold)
  File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 82, in yolo3_postprocess_np
    predictions = yolo_head(yolo_outputs, anchors, num_classes, input_dims=model_image_size)
  File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 29, in yolo_head
    results.append(_yolo_head(prediction, num_classes, anchors[anchor_mask[i]], input_dims))
  File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 41, in _yolo_head
    (batch_size, num_anchors * grid_size * grid_size, num_classes + 5))
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/dk-tanmay/.virtualenvs/cv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/dk-tanmay/.virtualenvs/cv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 43095 into shape (1,507,25)
```
Here the annotations.txt is custom and perfectly aligns with the kind of labels the model requires.
I tried running the model in inference mode and it runs perfectly.
How do I resolve the error ?

**Comment by david8862** [comment]
Hi, the "yolov3-tiny.h5" is trained on COCO dataset. So the class label file should be "configs/coco_classes.txt"

> I gave the following command
> `python eval.py --model_path=./weights/yolov3-tiny.h5 --anchors_path=configs/tiny_yolo_anchors.txt --classes_path=configs/voc_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.001 --annotation_file=annotations.txt --save_result`
> 
> This is the error I got
> 
> ```
> Traceback (most recent call last):
>   File "eval.py", line 932, in <module>
>     main()
>   File "eval.py", line 928, in main
>     eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
>   File "eval.py", line 863, in eval_AP
>     pred_classes_records = get_prediction_class_records(model_path, annotation_records, anchors, class_names, model_image_size, conf_threshold, save_result)
>   File "eval.py", line 168, in get_prediction_class_records
>     pred_boxes, pred_classes, pred_scores = yolo3_postprocess_np(model.predict([image_data]), image_shape, anchors, len(class_names), model_image_size, max_boxes=100, confidence=conf_threshold)
>   File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 82, in yolo3_postprocess_np
>     predictions = yolo_head(yolo_outputs, anchors, num_classes, input_dims=model_image_size)
>   File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 29, in yolo_head
>     results.append(_yolo_head(prediction, num_classes, anchors[anchor_mask[i]], input_dims))
>   File "/home/dk-tanmay/Desktop/keras-YOLOv3-model-set/yolo3/postprocess_np.py", line 41, in _yolo_head
>     (batch_size, num_anchors * grid_size * grid_size, num_classes + 5))
>   File "<__array_function__ internals>", line 6, in reshape
>   File "/home/dk-tanmay/.virtualenvs/cv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
>     return _wrapfunc(a, 'reshape', newshape, order=order)
>   File "/home/dk-tanmay/.virtualenvs/cv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
>     return bound(*args, **kwds)
> ValueError: cannot reshape array of size 43095 into shape (1,507,25)
> ```
> 
> Here the annotations.txt is custom and perfectly aligns with the kind of labels the model requires.
> I tried running the model in inference mode and it runs perfectly.
> How do I resolve the error ?
