### ISSUE TITLE
Letterbox_resize() produce different results for PIL and OpenCV

### ISSUE THREAD

**Issue by mvanlierBCG** [david8862/keras-YOLOv3-model-set#22]
I try to replace the letterbox_resize() functions in common/data_utils.py. But I can't get the same or closed result. Just to be sure, I use the correct order of width and height, and I have also converted the color format from BGR2RGB.

My letterbox_resize function with OpenCV is as follows:

```
def letterbox_resize_cv2(img, target_size, dataset_img_shape, return_padding_info=False):
    padColor = 128
    w, h = dataset_img_shape
    sw, sh = target_size

    # interpolation method
    if h > sh or w > sw: # shrinking image
        interp = cv2.INTER_AREA

    else: # stretching image
        interp = cv2.INTER_CUBIC

    # aspect ratio of image
    aspect = float(w)/h 
    saspect = float(sw)/sh

    if (saspect > aspect) or ((saspect == 1) and (aspect <= 1)):  # new horizontal image
        new_h = sh
        new_w = np.round(new_h * aspect).astype(int)
        pad_horz = float(sw - new_w) / 2
        pad_left, pad_right = np.floor(pad_horz).astype(int), np.ceil(pad_horz).astype(int)
        pad_top, pad_bot = 0, 0

    elif (saspect < aspect) or ((saspect == 1) and (aspect >= 1)):  # new vertical image
        new_w = sw
        new_h = np.round(float(new_w) / aspect).astype(int)
        pad_vert = float(sh - new_h) / 2
        pad_top, pad_bot = np.floor(pad_vert).astype(int), np.ceil(pad_vert).astype(int)
        pad_left, pad_right = 0, 0

    # set pad color
    if len(img.shape) is 3 and not isinstance(padColor, (list, tuple, np.ndarray)): # color image but only one color provided
        padColor = [padColor]*3

    # scale and pad
    scaled_img = cv2.resize(img, (new_w, new_h), interpolation=interp)
    scaled_img = cv2.copyMakeBorder(scaled_img, pad_top, pad_bot, pad_left, pad_right, borderType=cv2.BORDER_CONSTANT, value=padColor)

    cv2.imshow("Image Object Detection", scaled_img)
    key = cv2.waitKey(10000)#pauses for 3 seconds before fetching next image
    if key == 27:#if ESC is pressed, exit loop
        cv2.destroyAllWindows()

    return scaled_img

```

It seems that more people have similar problems, but it is still unsolved see the following link:
https://github.com/qqwweee/keras-yolo3/issues/330

Can someone give some hints about what may be the problem?

**Comment by david8862** [comment]
Hi @mvanlierBCG, I tried your cv2 version of letterbox_resize as image preprocess for model inference. It works somehow fine for that:

```
python validate_yolo.py --model_path=yolo3_nano.h5 --image_file=../example/dog.jpg --anchors_path=../configs/yolo3_anchors.txt --classes_path=../configs/voc_classes.txt
```

PIL version:
```
Found 4 boxes for ../example/dog.jpg
Class: car, Score: 0.6375207580741034, Box: (455, 85),(700, 158)
Class: bicycle, Score: 0.5200505846007424, Box: (57, 154),(615, 442)
Class: car, Score: 0.21803297248282405, Box: (61, 77),(97, 128)
Class: dog, Score: 0.17276230953302552, Box: (127, 206),(302, 566)
```

your cv2 version:
```
Found 4 boxes for ../example/dog.jpg
Class: car, Score: 0.6614284077894084, Box: (455, 85),(699, 157)
Class: bicycle, Score: 0.42565476108370603, Box: (57, 155),(616, 441)
Class: dog, Score: 0.20200887374322107, Box: (128, 205),(302, 566)
Class: car, Score: 0.18828738776850074, Box: (61, 77),(97, 127)
```

**Comment by A7med01** [comment]
def letterbox_image(img, inp_dim):
    '''resize image with unchanged aspect ratio using padding'''
    img_w, img_h = img.shape[1], img.shape[0]
    w, h = inp_dim
    new_w = int(img_w * min(w/img_w, h/img_h))
    new_h = int(img_h * min(w/img_w, h/img_h))
    resized_image = cv2.resize(img, (new_w,new_h), interpolation = cv2.INTER_CUBIC)
    
    canvas = np.full((inp_dim[1], inp_dim[0], 3), 128)

    canvas[(h-new_h)//2:(h-new_h)//2 + new_h,(w-new_w)//2:(w-new_w)//2 + new_w,  :] = resized_image
    
    return canvas

**Comment by A7med01** [comment]
this works :

def letterbox_image(img, inp_dim):
    '''resize image with unchanged aspect ratio using padding'''
    img_w, img_h = img.shape[1], img.shape[0]
    w, h = inp_dim
    new_w = int(img_w * min(w/img_w, h/img_h))
    new_h = int(img_h * min(w/img_w, h/img_h))
    resized_image = cv2.resize(img, (new_w,new_h), interpolation = cv2.INTER_CUBIC)
    canvas = np.full((inp_dim[1], inp_dim[0], 3), 128)
    canvas[(h-new_h)//2:(h-new_h)//2 + new_h,(w-new_w)//2:(w-new_w)//2 + new_w,  :] = resized_image
    return canvas
