### ISSUE TITLE
Inference with .h5/.tflite model for deployment

### ISSUE THREAD

**Issue by d-duran** [david8862/keras-YOLOv3-model-set#225]
Hello David,

I have successfully trained a yolo3_mobilenet_lite with the default training parameters from the README file.
I have also converted the .h5 model to a Quantized TFLite model.

Now I wonder how should we use these models for deployment. The prediction functions depend on `keras-YOLOv3-model-set` library being available with all the dependencies for image collection, preprocessing, interpreter creation, prediction... However, a deployment device should eventually not have installed the library due to storage constraints. Am I right?

What is the correct approach to be able to use a trained .h5/.tflite model for image bbox prediction? Would be "taking" the `class YOLO` code within `yolo.py` enough to create an object and invoke the interpreter for each individual image with `predict` method?

Thanks!

**Comment by david8862** [comment]
@d-duran  seems you've found validate_yolo.py :)
