### ISSUE TITLE
TFlite bad results

### ISSUE THREAD

**Issue by LilNader** [david8862/keras-YOLOv3-model-set#23]
Hi David,

I've downloaded your pre-trained yolo3_mobilnet_lite_416_voc.h5 model, I've tested it using this command
`python yolo.py --model_type=yolo3_mobilenet_lite --weights_path=yolo3_mobilnet_lite_416_voc.h5 --anchors_path=configs/yolo3_anchors.txt --classes_path=configs/voc_classes.txt --image`
IT WORKED FINE!
However, when I converted it to TFLite model using `tflite_convert --keras_model_file=yolo3_mobilnet_lite_416_voch5 --output_file=model.tflite`
Then, I tested it using this command
`python tools/validate_yolo.py --model_path=model.tflite --anchors_path=configs/yolo3_anchors.txt --classes_path=configs/voc_classes.txt --image_file=example/dog.jpg --loop_count=5`

I got this result 
![image](https://user-images.githubusercontent.com/37120481/75129351-42609180-56d1-11ea-8f94-bd77dc1f9a18.png)

This also happened with my custom trained model
I would greatly appreciate it if you could help me, Thank you!

**Comment by david8862** [comment]
Hi @LilNader , many thanks for the info. What's your TF version? I found this issue just happens on yolo3_mobilenet_lite model type and TF 2.x. So you maybe you can try to switch to TF 1.x if you want to keep using this model type or switch to other models (tiny_yolo3_mobilenet_lite/yolo3_nano/etc.) if you need to keep the TF version.
I guess it should be a TFLite 2.x converter bug, but didn't dig into the root cause.

**Comment by LilNader** [comment]
Hi @david8862 , Thank you for your quick response
I've switched to TF 1.14 and I got this error message
" Init node conv_dw_1/depthwise_kernel/Assign doesn't exist in graph"
I think it is related to the mobilenet architecture

**Comment by david8862** [comment]
> Hi @david8862 , Thank you for your quick response
> I've switched to TF 1.14 and I got this error message
> " Init node conv_dw_1/depthwise_kernel/Assign doesn't exist in graph"
> I think it is related to the mobilenet architecture

That should be just a warning and didn't impact .tflite model generation or inference result. Do you meet any problem with it?

**Comment by LilNader** [comment]
> That should be just a warning and didn't impact .tflite model generation or inference result. Do you meet any problem with it?

No it worked! 👍 
I just didn't see the model.tflite file, I saved it in different path
