### ISSUE TITLE
Box coodinates

### ISSUE THREAD

**Issue by MrVanq** [david8862/keras-YOLOv3-model-set#238]
I am having issues converting a dataset (Tsinghua-Daimler Cyclist) to the xmin,ymin,xmax,ymax format, when visualizing with dataset_visualize.py, I am getting wrong bounding boxes for far away objects (for objects closer it shows almost correct boxes) or an out of index error when trying to run it.
Could you tell me where the zero point of the coordinates is, is it top left or bottom left of the picture?
0-------------------x
|
|
|
y

or

y
|
|
|
0-------------------x

Like so?
![Screenshot 2022-11-19 011543](https://user-images.githubusercontent.com/96481194/202823489-3debc978-b54d-467e-b73e-f481d908b317.png)

**Comment by david8862** [comment]
> I am having issues converting a dataset (Tsinghua-Daimler Cyclist) to the xmin,ymin,xmax,ymax format, when visualizing with dataset_visualize.py, I am getting wrong bounding boxes for far away objects (for objects closer it shows almost correct boxes) or an out of index error when trying to run it. Could you tell me where the zero point of the coordinates is, is it top left or bottom left of the picture? 0-------------------x | | | y
> 
> or
> 
> y | | | 0-------------------x
> 
> Like so? ![Screenshot 2022-11-19 011543](https://user-images.githubusercontent.com/96481194/202823489-3debc978-b54d-467e-b73e-f481d908b317.png)

should be top-left:
0-------------------x
|
|
|
y

**Comment by MrVanq** [comment]
Thanks David, it worked.
Another question: there is no loss/postprocess and so on for yolov4, are you planning on implementing those? Is it right that you can only train yolov2/v3/v5 from this repo? 
I want to train the smallest available yolov4 model (tiny_yolo4lite_mobilenetv3small_body) or is it maybe possible to make (yolo5lite_mobilenetv2_body) smaller by leaving out f3 and what should I adapt? Sorry if it's a newbie question.

**Comment by david8862** [comment]
> Thanks David, it worked.
> Another question: there is no loss/postprocess and so on for yolov4, are you planning on implementing those? Is it right that you can only train yolov2/v3/v5 from this repo?
> I want to train the smallest available yolov4 model (tiny_yolo4lite_mobilenetv3small_body) or is it maybe possible to make (yolo5lite_mobilenetv2_body) smaller by leaving out f3 and what should I adapt? Sorry if it's a newbie question.

for yolo4 model family, the data_loader/loss/postprocess part has been merged to yolo3 since they share same architecture in this repo (see [model.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/yolo3/model.py))
regarding yolov5, it's just an experimental and not well verified implementation, so I didn't expand to many other model structures.

**Comment by MrVanq** [comment]
I see now, thanks for your replies.
Would be really nice if you could provide some best practice when it comes to training on your own dataset.
I want to train a model first with the COCO dataset and then with 2 other datasets.

COCO Training: --transfer_epoch 20 --total_epoch 50 --freeze_level 1
Dataset 1: --weights_path coco_trained.h5 --freeze_level 0 --transfer_epoch 0 --total_epoch 50 --init_epoch 50?  (idk what the difference between freeze_level 'None' and 0 is and does "only open prediction layer" mean that only the open prediction layer is frozen or all others except those are frozen)
Dataset 2: --weights_path dataset1_trained.h5 --freeze_level 0 --transfer_epoch 0 --total_epoch 50 --init_epoch 100?

Those 2 datasets include the few key classes that I want to detect, the COCO Training is just for the accuracy, should the freeze_level on those trainings be 0, 1 or 2.

And also is it correct to add those epochs for the init epoch of the next training?

**Comment by MrVanq** [comment]
I have tried training with the COCO Dataset on "tiny_yolo4lite_mobilenetv3small" and it shows the following error:

File "C:\Users\xyz\.conda\envs\yolo\lib\site-packages\tensorflow\python\util\module_wrapper.py", line 232, in _getattr
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'keras.api._v1.keras.experimental' has no attribute 'PeepholeLSTMCell'

**Comment by david8862** [comment]
> I see now, thanks for your replies. Would be really nice if you could provide some best practice when it comes to training on your own dataset. I want to train a model first with the COCO dataset and then with 2 other datasets.
> 
> COCO Training: --transfer_epoch 20 --total_epoch 50 --freeze_level 1 Dataset 1: --weights_path coco_trained.h5 --freeze_level 0 --transfer_epoch 0 --total_epoch 50 --init_epoch 50? (idk what the difference between freeze_level 'None' and 0 is and does "only open prediction layer" mean that only the open prediction layer is frozen or all others except those are frozen) Dataset 2: --weights_path dataset1_trained.h5 --freeze_level 0 --transfer_epoch 0 --total_epoch 50 --init_epoch 100?
> 
> Those 2 datasets include the few key classes that I want to detect, the COCO Training is just for the accuracy, should the freeze_level on those trainings be 0, 1 or 2.
> 
> And also is it correct to add those epochs for the init epoch of the next training?

if you do want to use COCO pretrained weights, you can try to enable `skip_mismatch=True` when loading weights (see [here](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/yolo3/model.py#L275) ) to avoid failure.
for training config you can refer `reference training config cmd` inf README
