### ISSUE TITLE
Question regarding faster model

### ISSUE THREAD

**Issue by Rakeshvcr** [david8862/keras-YOLOv3-model-set#24]
Hi David,

I have question to ask, is there any yolo or ssd model that can able to detect object in real time, like getting more than 20fps without using gpu. I tested yolo_nano but got only 5fps without gpu.
I needed a model that can perform well in browser, non of the model gave a good results.
Does removing few layers would help in achieving the speed?

**Comment by david8862** [comment]
> Hi David,
> 
> I have question to ask, is there any yolo or ssd model that can able to detect object in real time, like getting more than 20fps without using gpu. I tested yolo_nano but got only 5fps without gpu.
> I needed a model that can perform well in browser, non of the model gave a good results.
> Does removing few layers would help in achieving the speed?

Hi @Rakeshvcr, as I know mobilenet-ssd and [tiny_yolo3_mobilnet_lite](https://github.com/david8862/keras-YOLOv3-model-set/releases/download/v1.0.0/tiny_yolo3_mobilnet_lite_320_voc.tar.gz) with 320x320 input size could achieve fastest object detection on CPU while having acceptable mAP performance. I've ever tested tiny_yolo3_mobilnet_lite_320 model on x64 PC and got ~40ms inference latency (see [here](https://github.com/david8862/keras-YOLOv3-model-set/tree/master/inference#you-can-also-use-evalpy-to-do-evaluation-on-the-mnn-model)). If you want to be even more faster, one possible solution is reduce the input size to lower down compute cost. But that will also impact the accuracy.

**Comment by Rakeshvcr** [comment]
Thank you for the suggestion I'll try using tiny_yolo3_mobilnet_lite_320
