### ISSUE TITLE
Eval.py on custom model

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [david8862/keras-YOLOv3-model-set#3]
I had previously trained a YOLO model using https://github.com/qqwweee/keras-yolo3 and have it's weights saved.
When I run the following command for evaluation 
`python eval.py --model_path=./weights/face_latest.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.50 --annotation_file=annotations.txt --save_result
`
where face_latest.h5 is my model and face_classes.txt contains 4 classes (top side down head) the following error pops up
```
Traceback (most recent call last):
  File "eval.py", line 931, in <module>
    main()
  File "eval.py", line 927, in main
    eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
  File "eval.py", line 862, in eval_AP
    pred_classes_records = get_prediction_class_records(model_path, annotation_records, anchors, class_names, model_image_size, conf_threshold, save_result)
  File "eval.py", line 155, in get_prediction_class_records
    model = load_model(model_path, compile=False)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 209, in load_model_from_hdf5
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

```
How do I fix the error ? 
A few more queries:
1. What is the IoU threshold supplied in the arguments used for ?
2. How is the VOC metric different from the COCO metric ?

**Comment by david8862** [comment]
The eval.py just use the saved model file to do the evaluation, but not just trained weights. So you need to follow [Model dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump) first to dump out the model from training weights or checkpoint, and then use it in eval.py.

1. The IoU threshold is a metric to check whether your predicted bounding box match a ground truth object box, by calculating IoU result between them and compared with threshold. In PascalVOC mAP evaluation it is set to 0.5, but you can also use other value to 

2. Just related to the previous question, VOC metric use 0.5 as IoU threshold but COCO got result on 0.5:0.95 and average them. Maybe you can read this blogpost [mAP (mean Average Precision) for Object Detection](https://medium.com/@jonathan_hui/map-mean-average-precision-for-object-detection-45c121a31173) for more explanation

> I had previously trained a YOLO model using https://github.com/qqwweee/keras-yolo3 and have it's weights saved.
> When I run the following command for evaluation
> `python eval.py --model_path=./weights/face_latest.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.50 --annotation_file=annotations.txt --save_result `
> where face_latest.h5 is my model and face_classes.txt contains 4 classes (top side down head) the following error pops up
> 
> ```
> Traceback (most recent call last):
>   File "eval.py", line 931, in <module>
>     main()
>   File "eval.py", line 927, in main
>     eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
>   File "eval.py", line 862, in eval_AP
>     pred_classes_records = get_prediction_class_records(model_path, annotation_records, anchors, class_names, model_image_size, conf_threshold, save_result)
>   File "eval.py", line 155, in get_prediction_class_records
>     model = load_model(model_path, compile=False)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
>     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 209, in load_model_from_hdf5
>     raise ValueError('No model found in config file.')
> ValueError: No model found in config file.
> ```
> 
> How do I fix the error ?
> A few more queries:
> 
> 1. What is the IoU threshold supplied in the arguments used for ?
> 2. How is the VOC metric different from the COCO metric ?

**Comment by tanmay-bhatnagar** [comment]
So if I supply an IoU threshold and select the PascalVOC metric along with it, will it override the current threshold and set it to the value I supplied ?

**Comment by david8862** [comment]
The "iou_threshold" option is only valid for VOC metric, to help you dig into the model performance on other IoU metrics rather than only on 0.5. For COCO output, it will bypass this Threshold and use standard 0.5:0.95

> So if I supply an IoU threshold and select the PascalVOC or COCO metric along with it, will it override the current threshold and set it to the value I supplied ?

**Comment by tanmay-bhatnagar** [comment]
I dumped my custom model and it was successful. On giving the following command for eval.py
`python eval.py --model_path=face_inference.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.1 --annotation_file=annotations.txt --save_result`

I get this error:

```
Traceback (most recent call last):
  File "eval.py", line 931, in <module>
    main()
  File "eval.py", line 927, in main
    eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
  File "eval.py", line 865, in eval_AP
    compute_mAP_PascalVOC(annotation_records, gt_classes_records, pred_classes_records, class_names, iou_threshold)
  File "eval.py", line 675, in compute_mAP_PascalVOC
    APs, mAP, iou_threshold)
  File "eval.py", line 595, in plot_Pascal_AP_result
    draw_plot_func(APs, num_classes, window_title, plot_title, x_label, output_path, to_show=False, plot_color='royalblue', true_p_bar='')
  File "eval.py", line 454, in draw_plot_func
    plt.barh(range(n_classes), sorted_values, color=plot_color)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2454, in barh
    y, width, height=height, left=left, align=align, **kwargs)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 2597, in barh
    align=align, **kwargs)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 2375, in bar
    np.atleast_1d(x), height, width, y, linewidth)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 259, in broadcast_arrays
    shape = _broadcast_shape(*args)
  File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 193, in _broadcast_shape
    b = np.broadcast(*args[:32])
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

Seems to be some sort of plotting error?
face_classes.txt contrain 4 classes (A,B,C,D)
annotations,txt has just 1 image annotation (I tried with multiple images, got the same error) with 11 ground truth boxes (A - 7 , B - 1 , C - 0, D - 3 )
Tell me if you require any other details

**Comment by david8862** [comment]
Could you provide your full running log? From current log you should have got "Ground-Truth_Info.jpg" and "Predicted_Objects_Info.jpg" chart under result/ dir. Maybe you can check them to see if the info is correct.

> I dumped my custom model and it was successful. On giving the following command for eval.py
> `python eval.py --model_path=face_inference.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --eval_type=VOC --iou_threshold=0.5 --conf_threshold=0.1 --annotation_file=annotations.txt --save_result`
> 
> I get this error:
> 
> ```
> Traceback (most recent call last):
>   File "eval.py", line 931, in <module>
>     main()
>   File "eval.py", line 927, in main
>     eval_AP(args.eval_type, args.model_path, args.annotation_file, anchors, class_names, args.iou_threshold, args.conf_threshold, model_image_size, args.save_result)
>   File "eval.py", line 865, in eval_AP
>     compute_mAP_PascalVOC(annotation_records, gt_classes_records, pred_classes_records, class_names, iou_threshold)
>   File "eval.py", line 675, in compute_mAP_PascalVOC
>     APs, mAP, iou_threshold)
>   File "eval.py", line 595, in plot_Pascal_AP_result
>     draw_plot_func(APs, num_classes, window_title, plot_title, x_label, output_path, to_show=False, plot_color='royalblue', true_p_bar='')
>   File "eval.py", line 454, in draw_plot_func
>     plt.barh(range(n_classes), sorted_values, color=plot_color)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2454, in barh
>     y, width, height=height, left=left, align=align, **kwargs)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 2597, in barh
>     align=align, **kwargs)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 2375, in bar
>     np.atleast_1d(x), height, width, y, linewidth)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 259, in broadcast_arrays
>     shape = _broadcast_shape(*args)
>   File "/home/dk-tanmay/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 193, in _broadcast_shape
>     b = np.broadcast(*args[:32])
> ValueError: shape mismatch: objects cannot be broadcast to a single shape
> ```
> 
> Seems to be some sort of plotting error?
> face_classes.txt contrain 4 classes (A,B,C,D)
> annotations,txt has just 1 image annotation (I tried with multiple images, got the same error) with 11 ground truth boxes (A - 7 , B - 1 , C - 0, D - 3 )
> Tell me if you require any other details

**Comment by tanmay-bhatnagar** [comment]
@david8862 https://drive.google.com/file/d/1waVenugbDHTJd0Q4Jvrtb9GQT_ZMwh4C/view?usp=sharing

**Comment by david8862** [comment]
It may be caused by some corner case handling in eval.py. I've commit some fix for that in
https://github.com/david8862/keras-YOLOv3-model-set/commit/f165f4641f26ee34b536e41c989c8f2f59b1e532

You can retry with latest code, and better to let your annotations.txt to have more testing ground truth boxes to cover all the target classes (4 in your face case)

> @david8862 https://drive.google.com/file/d/1waVenugbDHTJd0Q4Jvrtb9GQT_ZMwh4C/view?usp=sharing
