### ISSUE TITLE
YOLO v4: Layer #119 (named "batch_normalization_35"), weight <tf.Variable 'batch_normalization_35/gamma:0' shape=(480,) dtype=float32> has shape (480,), but the saved weight has shape (128,).

### ISSUE THREAD

**Issue by nospotfer** [david8862/keras-YOLOv3-model-set#35]
Hello!
I'm trying to train Yolov4 on my own dataset. 
I've followed the steps to download weights and re-order the output tensors --> **OK**!
With this I get a yolov4.h5

Now i'm trying to train with:
`python train.py --model_type=yolo4_mobilenetv3large --anchors_path=configs/yolo4_anchors.txt --weights_path=/home/gabriel/git/keras-YOLOv3-model-set/weights/yolov4.h5 --annotation_file=/home/gabriel/Pictures/_LABELS_/list_file.txt --classes_path=/home/gabriel/Pictures/_LABELS_/classes_v4.txt --eval_online --save_eval_checkpoint --freeze_level=1 --batch_size=8 --val_split=0.1 --model_image_size=512x512`

and I get:
`model layer number: 315
Traceback (most recent call last):
  File "train.py", line 258, in <module>
    main(args)
  File "train.py", line 114, in main
    model = get_train_model(args.model_type, anchors, num_classes, weights_path=args.weights_path, freeze_level=freeze_level, optimizer=optimizer, label_smoothing=args.label_smoothing, model_pruning=args.model_pruning, pruning_end_step=pruning_end_step)
  File "/home/gabriel/git/keras-YOLOv3-model-set/yolo3/model.py", line 198, in get_yolo3_train_model
    model_body.load_weights(weights_path, by_name=True)#, skip_mismatch=True)
  File "/home/gabriel/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/gabriel/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1422, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/gabriel/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 820, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #119 (named "batch_normalization_35"), weight <tf.Variable **'batch_normalization_35/gamma:0' shape=(480,) dtype=float32> has shape (480,), but the saved weight has shape (128,)**.
`
Any hints on how to approach this? 
Thank you!

**Comment by david8862** [comment]
Hi @nospotfer , in your training config you're using "yolo4_mobilenetv3large" model type. If so you don't need to load the official YOLOv4 model weights by "--weights_path=.../weights/yolov4.h5". model construction part will download MobileNetv3_Large Imagenet pretrained weights automatically as backbone for transfer training base

**Comment by nospotfer** [comment]
Thank you! This worked great for me!
