### ISSUE TITLE
Evaluation curves

### ISSUE THREAD

**Issue by Mostafa-elgendy** [david8862/keras-YOLOv3-model-set#36]
How to draw the accuracy and loss curves using your project on a custom dataset?
How to also draw the precision-recall curve for a custom dataset which have five classes for example?
Is it possible to draw a precision-recall curve to compare different models like comparing yolov3 and tiny-yolov3 on a custom dataset?

**Comment by david8862** [comment]
Hi @Mostafa-elgendy, you can refer [Evaluation](https://github.com/david8862/keras-YOLOv3-model-set#evaluation) part to do evaluation on your dataset, the eval tool will draw the P-R curve for each class in dataset. For comparison of different type models you may need to train every model and do the evaluation on them to get different P-R curves

**Comment by Mostafa-elgendy** [comment]
Thanks a lot for your answer. I want to ask also about:
1- How to draw the accuracy and loss curves using your project on a custom dataset?
2- The peak signal-to-noise ratio (PSNR) has been widely used for performance evaluation so, How to measure it during training your model on my own dataset?

**Comment by david8862** [comment]
> Thanks a lot for your answer. I want to ask also about:
> 1- How to draw the accuracy and loss curves using your project on a custom dataset?
> 2- The peak signal-to-noise ratio (PSNR) has been widely used for performance evaluation so, How to measure it during training your model on my own dataset?

Hi @Mostafa-elgendy 
1-For loss curves you can check from tensorboard with 

```
# tensorboard --logdir=logs/000
```

for model accuracy, currently the most common accuracy metric for object detection algorithm are PascalVOC mAP or COCO AP. You can use "--eval_online" and related options to check it during training, but I haven't recorded that and draw a curve yet.

2-I didn't add PSNR evaluation support in this repo now
