### ISSUE TITLE
Can yolo4 be converted to pb or onnx？

### ISSUE THREAD

**Issue by iFlyyyy** [david8862/keras-YOLOv3-model-set#39]
thanks for the great job ！

**Comment by david8862** [comment]
.pb works and has been verified.  .onnx convert meet following error:

  File "/root/.virtualenvs/py3ml_2/lib/python3.6/site-packages/keras2onnx/ke2onnx/activation.py", line 70, in convert_keras_activation
    raise RuntimeError("Unsupported activation method within Activation layer '{}'".format(activation))
RuntimeError: Unsupported activation method within Activation layer '<function mish at 0x7f7190f8f7b8>'

seems keras2onnx has not support new mish activation layer

**Comment by gan3sh500** [comment]
Hey @david8862 I was able to get this working and tflite. Requires a few different changes. 

1) Using keras to savedmodel format, then using tensorflow2onnx. 
2) Changing inference scripts for validate_yolo.py and eval.py to sort the predictions according to shape i.e. keras gives [1, 13, 13, x] then [1, 26, 26, x] and [1, 52, 52, x] but onnx and tflite give wrong order so should be sorted. 
3) For tflite requires writing softplus again as combination of log and exp. 

Can I submit these as a PR. Will solve some previous issue someone mentioned with mish as well as not requiring tf 1.x to do keras2onnx.

**Comment by david8862** [comment]
> Hey @david8862 I was able to get this working and tflite. Requires a few different changes.
> 
> 1. Using keras to savedmodel format, then using tensorflow2onnx.
> 2. Changing inference scripts for validate_yolo.py and eval.py to sort the predictions according to shape i.e. keras gives [1, 13, 13, x] then [1, 26, 26, x] and [1, 52, 52, x] but onnx and tflite give wrong order so should be sorted.
> 3. For tflite requires writing softplus again as combination of log and exp.
> 
> Can I submit these as a PR. Will solve some previous issue someone mentioned with mish as well as not requiring tf 1.x to do keras2onnx.

@gan3sh500  sure. Code contribution is warmly welcomed :)
