### ISSUE TITLE
Import error in yolo.py

### ISSUE THREAD

**Issue by tanmay-bhatnagar** [david8862/keras-YOLOv3-model-set#4]
I ran the following command to create a model dump:
`python yolo.py --model_type=darknet --model_path=weights/face_latest.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --output_model_file=dump.h5 --dump_model`
Received the following error:
```
Traceback (most recent call last):
  File "yolo.py", line 17, in <module>
    from tensorflow_model_optimization.sparsity import keras as sparsity
```
Tried out various versions of tf-gpu(1.13 , 1.12, 1.6), same error persists. Was not getting this error in one of the earlier versions of the repo.
Which tensorflow version are you using ?

**Comment by david8862** [comment]
Try to add another package with
```
pip install tensorflow-model-optimization
```
It's a new added tensorflow component for model quantization & pruning and better to work with some new TF release (e.g. 1.14.0 and later)

> I ran the following command to create a model dump:
> `python yolo.py --model_type=darknet --model_path=weights/face_latest.h5 --anchors_path=configs/yolo_anchors.txt --classes_path=configs/face_classes.txt --model_image_size=416x416 --output_model_file=dump.h5 --dump_model`
> Received the following error:
> 
> ```
> Traceback (most recent call last):
>   File "yolo.py", line 17, in <module>
>     from tensorflow_model_optimization.sparsity import keras as sparsity
> ```
> 
> Tried out various versions of tf-gpu(1.13 , 1.12, 1.6), same error persists. Was not getting this error in one of the earlier versions of the repo.
> Which tensorflow version are you using ?
