### ISSUE TITLE
Error encountered during training [TypeError: unhashable type: '_DictWrapper']

### ISSUE THREAD

**Issue by peterryan13** [david8862/keras-YOLOv3-model-set#48]
Hi David,

Thank you for all the great work that you do!

I encountered the following error when training using Yolo v3 (I am trying training as part of my study of machine learning). The training actually proceeded around 15 days ago and I started to encounter this error when I upgraded to TF 2.2 (I was previously using TF 2.1). I am using a Windows environment.

![image](https://user-images.githubusercontent.com/56289207/82972284-428d6780-a007-11ea-942a-01e5e4bad614.png)

Training command:
![image](https://user-images.githubusercontent.com/56289207/82971844-440a6000-a006-11ea-80bd-4011297c3d6d.png)

I also tried using Adagrad and Adadelta. The error is now encountered regardless of the optimizer. Previously, I used the default (Adam).

Do you have any idea regarding this? I am currently looking into base_layer.py, functional.py, and data_structures.py but I haven't found the solution yet.

**Comment by david8862** [comment]
@peterryan13, are you using the latest code? It's a model compile issue on TF 2.2 and I just fix it recently

**Comment by peterryan13** [comment]
I just cloned the latest code today and I'm downloading the weights for Yolo v4 to try that too. I'll get back to you soon.

**Comment by peterryan13** [comment]
Hi David, 

You're right. Sorry for bothering you and thanks again!
