### ISSUE TITLE
get_yolo3_train_model里面y_true的疑问

### ISSUE THREAD

**Issue by zhiyoujingtian** [david8862/keras-YOLOv3-model-set#49]
y_true = [Input(shape=(None, None, 3, num_classes+5), name='y_true_{}'.format(l)) for l in range(num_feature_layers)]

    model_body, backbone_len = get_yolo3_model(model_type, num_feature_layers, num_anchors, num_classes, model_pruning=model_pruning, pruning_end_step=pruning_end_step)
  
yolov3的y_true不应该是这个样子么：
    y_true = [Input(shape=(h//{0:32, 1:16, 2:8}[l], w//{0:32, 1:16, 2:8}[l], num_anchors//3, num_classes+5)) for l in range(3)]

您能帮忙解释一下么

**Comment by david8862** [comment]
这里是为了适应multiscale training，让train model的h和w成为可变的尺寸，以适应不同输入image shape所对应的不同featuremap size

**Comment by zhiyoujingtian** [comment]
在训练的时候，指定了图片的输入大小，这个位置也需要这样适应？  不是很懂，麻烦您啦

**Comment by david8862** [comment]
如果不考虑multiscale training，而是固定输入图片尺寸的话，是可以不需要的

**Comment by zhiyoujingtian** [comment]
> 如果不考虑multiscale training，而是固定输入图片尺寸的话，是可以不需要的
原版的yolov3,y_true改成您写的这个样子，训练同样数据的话， 多尺度训练  ，模型的map能提高么？
不知道您有没有尝试，我的计算资源有限，想请教一下您

**Comment by zhiyoujingtian** [comment]
针对同样的数据，yolov3训练改成您这个样子，利用multiscale training 能提高map么 ，不知道您有没有这方面的尝试或者经验

**Comment by david8862** [comment]
对于标准YOLOv3结构和PascalVOC, COCO这些公开数据集而言是有帮助的。如果换成轻量级的backbone和head的话，效果会有所减弱。另外在其他特定的数据集上的效果如何也要视具体数据分布而定

> 针对同样的数据，yolov3训练改成您这个样子，利用multiscale training 能提高map么 ，不知道您有没有这方面的尝试或者经验

**Comment by zhiyoujingtian** [comment]
Thanks♪(･ω･)ﾉ
