### ISSUE TITLE
use  yolo4_efficientnet  train own data

### ISSUE THREAD

**Issue by zhiyoujingtian** [david8862/keras-YOLOv3-model-set#51]
利用 yolo4_efficientnet训练自己的数据，骨干网络加载了  efficientnet的预训练权重

1.  那yolo4_predictions部分的权重是怎么办？重新训练么  

2. 如果是重新训练，efficientnet的权重全部Freeze，其他层全部Unfreeze 训练么 ？

**Comment by david8862** [comment]
通常的方式是先Freeze backbone部分，单独训练head若干个epoch，之后Unfreeze进行端到端的fine tune

**Comment by zhiyoujingtian** [comment]
> 通常的方式是先Freeze backbone部分，单独训练head若干个epoch，之后Unfreeze进行端到端的fine tune
好的，谢谢大佬

**Comment by zhiyoujingtian** [comment]
利用efficientnet4作为backbone 
backbone layers number: 472
model layer number: 539
预训练的时候
Freeze the first 472 layers of total 539 layers
第一轮 训练的时候
1/1 [==============================] - 11s 11s/step - loss: nan - location_loss: nan - confidence_loss: 472836.3750 - class_loss: 1819.8953
location_loss利用的是 use_diou_loss
在端到端训练前，如何能训练出一个稳定的头部

**Comment by zhiyoujingtian** [comment]
利用efficientnet4作为backbone
backbone layers number: 472
model layer number: 539
预训练的时候
Freeze the first 472 layers of total 539 layers
第一轮 验证的时候
 1/20 [>.............................] - ETA: 2:53 - loss: nan - location_loss: nan - confidence_loss: 229.0997 - class_loss: 10.4447
 2/20 [==>...........................] - ETA: 2:29 - loss: nan - location_loss: nan - confidence_loss: 218.1225 - class_loss: 11.0659
 3/20 [===>..........................] - ETA: 2:17 - loss: nan - location_loss: nan - confidence_loss: 215.4475 - class_loss: 10.2718
 4/20 [=====>........................] - ETA: 2:05 - loss: nan - location_loss: nan - confidence_loss: 215.0493 - class_loss: 10.7605
location_loss利用的是 use_diou_loss
在端到端训练前，如何能训练出一个稳定的头部

**Comment by david8862** [comment]
对于大模型可以考虑使用sgd优化器，有利于在初始阶段快速收敛，得到相对稳定的head

**Comment by zhiyoujingtian** [comment]
嗯嗯 谢谢，可以  还试过另外一种方法，warmup  先设置很低的学习率，跑几轮后，就不会出现nan了
