### ISSUE TITLE
Question training issue

### ISSUE THREAD

**Issue by yannishin** [david8862/keras-YOLOv3-model-set#55]
When learning, the warning below is being logged.
(With my custom data)

How to solve this warning ?

I used this option.
--model_type=yolo4_darknet
--model_image_size=960*1280

python train.py --model_type=yolo4_darknet --anchors_path=configs/yolo3_anchors.txt --weights_path=weights=yolov5.h5 --annotation_file=/workspace/data/final/plate/train.csv --classes_path=/workspace/data/final/plate/plate_classes.txt --model_image_size=960*1280 --eval_online --save_eval_checkpoint

----------- Warning Message --------------
E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)

**Comment by david8862** [comment]
Seems it's a legacy issue from keras-yolo3:
https://stackoverflow.com/questions/57558476/training-a-keras-model-yields-multiple-optimizer-errors
I've commit fix for it. You can have a try on latest code

**Comment by yannishin** [comment]
Thank you very much!!!
I solved this issue.
