### ISSUE TITLE
Could you please help me in converting the yolov4_mobilenet tf.keras model to .pb models?

### ISSUE THREAD

**Issue by ShihuaiXu** [david8862/keras-YOLOv3-model-set#57]

**Comment by david8862** [comment]
you can refer [model-dump](https://github.com/david8862/keras-YOLOv3-model-set#model-dump) and [tensorflow-model-convert](https://github.com/david8862/keras-YOLOv3-model-set#tensorflow-model-convert) for .pb model convert

**Comment by ShihuaiXu** [comment]
thank you very much, I would like to try it.





------------------ Original ------------------
