### ISSUE TITLE
工程运行的版本（调用不起来GPU）

### ISSUE THREAD

**Issue by Aurorayy** [david8862/keras-YOLOv3-model-set#72]
Thanks for sharing~
当运行train.py后，发现训练速度很慢，然后发现是GPU根本没使用。
已装了tensorflow-gpu==1.2.1、tensorflow==1.14.0、keras==2.1.2、CUDA8、python3.5
另外请问作者运行的各个版本是什么，谢谢。

**Comment by david8862** [comment]
验证过的环境包括tensorflow-gpu 1.14/1.15/2.2，基于CUDA 10.0或10.1
TF 1.2.1应该是不支持的
