### ISSUE TITLE
yolo3_darknet_spp error

### ISSUE THREAD

**Issue by mvanlierBCG** [david8862/keras-YOLOv3-model-set#77]
When using `yolov3_darknet_spp` and loading for training I get the following error:

`ValueError: No such layer: leaky_re_lu_58`

This error comes from `yolo3.models.yolo3_darknet.py` --> `custom_yolo3_spp_body()`.

My guess is that is since you get the layer by name:
```
    y1 = base_model.get_layer('leaky_re_lu_58').output
    y2 = base_model.get_layer('leaky_re_lu_65').output
    y3 = base_model.get_layer('leaky_re_lu_72').output
    y1 = DarknetConv2D(num_anchors*(num_classes+5), (1,1), name='prediction_13')(y1)
    y2 = DarknetConv2D(num_anchors*(num_classes+5), (1,1), name='prediction_26')(y2)
    y3 = DarknetConv2D(num_anchors*(num_classes+5), (1,1), name='prediction_52')(y3)
```
 
I think you have this already fixed by in the regular yolov3 darknet: `yolo3_body()` by calling the number of the layers.

I see that there is also `yolo3_spp_body()`, which calls the layers by number can I use that function instead?

**Comment by david8862** [comment]
@mvanlierBCG  yes, the better way is using index to get layer. I'll fix the yolo3_darknet_spp case later.

**Comment by mvanlierBCG** [comment]
@david8862 Thanks for fixing!
