### ISSUE TITLE
AssertionError: Only stride=2 supported.

### ISSUE THREAD

**Issue by dsbyprateekg** [david8862/keras-YOLOv3-model-set#93]
Hi,

I am trying to convert my custom YOLOv4 weights to TF but getting below error-
![stride2](https://user-images.githubusercontent.com/30830541/87543403-53329380-c6c2-11ea-9aae-4c4a7f0a526f.JPG)

I have attached my cfg file. Please add support to this.
[yolo-obj.txt](https://github.com/david8862/keras-YOLOv3-model-set/files/4925056/yolo-obj.txt)

**Comment by david8862** [comment]
@dsbyprateekg  Done. I've updated the strides limit in upsample convert. You can have a try again.

**Comment by dsbyprateekg** [comment]
Thanks @david8862 !
After the code update, I am able to do the conversion successfully.
