### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_model_optimization'

### ISSUE THREAD

**Issue by dsbyprateekg** [david8862/keras-YOLOv3-model-set#94]
Hi,

I have converted my custom YOLOv4 model into TF successfully. Now when I run the command `python yolo.py --image` I am getting below error-
![test_image](https://user-images.githubusercontent.com/30830541/87627795-25def780-c74d-11ea-9cf9-500e9603bc65.JPG)

I tried to install `pip install tensorflow-model-optimization`, but getting same error.
My TensorFlow version is 2.0.0
I have verified the same error in TensorFlow version 2.2.0 also.
Please suggest how to solve this error.

**Comment by dsbyprateekg** [comment]
Hi,

I have solved the above error in Google Colab after installing `pip install tensorflow-model-optimization`

Now I have put my obj.text file inside configs folder, make required changes in yolo.py file wrt to yolov4 as below-
![yolo_4](https://user-images.githubusercontent.com/30830541/87633538-2d0c0280-c759-11ea-9218-2feb5d6f8288.JPG)

But getting below error-
![yolo4_error](https://user-images.githubusercontent.com/30830541/87633599-48770d80-c759-11ea-9471-0df0f00b40df.JPG)

Please provide support for YOLOv4 custom model in yolo.py file.

**Comment by dsbyprateekg** [comment]
Hi @david8862 ,
Have you got any chance to add YOLOv4 support in yolo.py file?

**Comment by david8862** [comment]
@dsbyprateekg yolo.py is for dumping and demo supported trained model. If you want to verify a third party YOLO model, try [validate_yolo.py](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py)

**Comment by dsbyprateekg** [comment]
@david8862 my aim is to after converting my YOLOv4 model into TF, how can I make prediction on new images and saves the result using this converted model?

**Comment by david8862** [comment]
@dsbyprateekg validate_yolo.py could do inference on different model types, including TF .h5 or .pb

**Comment by dsbyprateekg** [comment]
Thanks @david8862 I am able to test my TF model in my test images.
