### ISSUE TITLE
Where this file is going to be used?

### ISSUE THREAD

**Issue by dikshaaswal** [david8862/keras-YOLOv3-model-set#95]
Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.6/mobilenet_1_0_224_tf_no_top.h5
17227776/17225924 [==============================] - 0s 0us/step

Can we explicitly download this file, as my server nodes don't have internet access ?

**Comment by david8862** [comment]
Sure. you can also manually download the weights file and put to $HOME/.keras/models/ (by default for Ubuntu). Then the auto download would bypass.
