### ISSUE TITLE
Where to set 'iou_thresh' value while using validate_yolo.py?

### ISSUE THREAD

**Issue by dsbyprateekg** [david8862/keras-YOLOv3-model-set#97]
Hi @david8862 ,

As you suggested previously I am able to use my converted TF model on new images using validate_yolo.py.
Can you please tell me how can I use '-iou_thresh' like we do below with Darknet while using validate_yolo.py -
`.\darknet.exe detector map data/obj.data cfg/yolo-obj.cfg backup/wheat/yolo-obj_best.weights -iou_thresh 0.05`

**Comment by david8862** [comment]
@dsbyprateekg  I didn't expose a CLI option to configure that. But there's a default kwargs "iou_threshold=0.4" for [yolo3_postprocess_np](https://github.com/david8862/keras-YOLOv3-model-set/blob/master/tools/evaluation/validate_yolo.py#L345) which you can manually change code to control it.

**Comment by dsbyprateekg** [comment]
Thanks @david8862 it resolves my query.
